<div style="font-family:arial;font-size:8pt;width:350px;line-height:10.5pt;">
	<div style="background-color:$Colour$;color:#FFFFFF;padding:1px 5px 0px 5px;width:340px;height:16px;">
		<div style="font-weight:bold;float:left;">$Name$</div>
		<div style="float:right;">$Level$</div>
	</div>
	<div style="background-color:#DDDDCC;background-image:url('$BackgroundImage$');font-style:italic;padding: 1px 0px 3px 5px;">$FlavourText$</div>
	<div style="padding-left:5px;">
		<span style="font-weight:bold;">$Usage$</span> ♦ <span style="font-weight:bold;">$Keywords:{key | $key$};seperator=", "$</span><br />
		<span style="font-weight:bold;">$Action$</span> ♦ <span style="font-weight:bold;">$Attack$</span> $Range$
	</div>
  $Type, Text, Indent, Shading:{Type, Text, Indent, Shading | ElementTemplate}$
  <br/>
</div>